task:
  type: preprocessing-irm
  data_dir: ${GENERATION_DATA_DIR}
  output_dir: ${REV_DATA_DIR}
  batch_size: 128
  generation_model:
    type: huggingface-wrapper-from-best
    path: ${GENERATION_MODEL}
  generation_collate_fn:
    type: ecqa-infilling-collate-fn
    rationale_format: ${RATIONALE_FORMAT}
    max_input_length: 256
    max_output_length: 64
    removal_threshold: ${THRESHOLD}
    intervention_on_label: True
  model_name: t5-base
  counterfactual_preprocessor:
    type: ecqa-counterfactual-generation-preprocessor
    batch_size: 16
  collate_fn:
    type: ecqa-irm-collate-fn
    rationale_format: ${RATIONALE_FORMAT}
    max_input_length: 512
    max_output_length: 32
  eval_collate_fn:
    type: ecqa-generation-collate-fn
    rationale_format: ${RATIONALE_FORMAT}
    max_input_length: 512
    max_output_length: 32
    intervention_on_label: True