task:
  type: preprocessing-irm
  data_dir: ${GENERATION_DATA_DIR}
  output_dir: ${REV_DATA_DIR}
  batch_size: 128
  generation_model:
    type: huggingface-wrapper-from-best
    path: ${GENERATION_MODEL}
  generation_collate_fn:
    type: strategyqa-infilling-collate-fn
    rationale_format: ${RATIONALE_FORMAT}
    max_input_length: 128
    max_output_length: 128
    removal_threshold: ${THRESHOLD}
    intervention_on_label: True
  model_name: microsoft/deberta-v3-large
  counterfactual_preprocessor:
    type: strategyqa-counterfactual-generation-preprocessor
    batch_size: 16
    device: "cuda:0"
  collate_fn:
    type: strategyqa-irm-embedding-classification-collate-fn
    rationale_format: ${RATIONALE_FORMAT}
    max_input_length: 128 
  eval_collate_fn:
    type: strategyqa-embedding-classification-collate-fn
    rationale_format: ${RATIONALE_FORMAT}
    max_input_length: 128