task:
  type: model-training
  batch_size: 256
  eval_batch_size: 2048
  num_epochs: 30
  vocab_path: data/strategyqa_vocabs/vocab_format=${RATIONALE_FORMAT}_ng=${NUM_NGRAMS}_mf=1_mt=${MAX_TOKENS}.pt
  model:
    type: fasttext-from-scratch
    embedding_dim: 100
    output_dim: 2
  trainer:
    type: "default"
    optimizer_constructor:
      type: adamw
      learning_rate: 0.1
    metrics:
      accuracy:
        type: classification-accuracy
      loss: 
        type: avg-loss
    eval_metrics:
      accuracy:
        type: classification-accuracy
      loss: 
        type: avg-loss
    main_metric: loss
    save_dir: ckpt/strategyqa_fasttext_format=${RATIONALE_FORMAT}_ng=${NUM_NGRAMS}_mf=${MIN_FREQ}_mt=${MAX_TOKENS}
    device: "cuda:0"
  datapath_train: data/strategyqa/removal_format=${RATIONALE_FORMAT}_ng=${NUM_NGRAMS}_mf=${MIN_FREQ}_mt=${MAX_TOKENS}/train
  datapath_eval: data/strategyqa/removal_format=${RATIONALE_FORMAT}_ng=${NUM_NGRAMS}_mf=${MIN_FREQ}_mt=${MAX_TOKENS}/validation
