task:
  type: "rev-test"
  batch_size: 8
  datapath_baseline: ${BASELINE_DATA_DIR}
  datapath_test: ${REV_DATA_DIR}
  output_path: ${REPORT_FILE}
  baseline_model:
    type: "huggingface-wrapper-from-best"
    path: ${BASELINE_MODEL}
  rev_model:
    type: "huggingface-wrapper-from-best"
    path: ${REV_MODEL}
  trainer:
    type: ecqa-baseline
    optimizer_constructor:
      type: adamw
      learning_rate: 0.0001
    metrics:
      loss:
        type: avg-loss
    eval_metrics:
      loss:
        type: avg-loss
      accuracy:
        type: classification-accuracy
    main_metric: loss
    save_dir: ${BASELINE_MODEL}