task:
  type: preprocessing-baseline
  data_dir: ${RAW_DATA_DIR}
  output_dir: ${BASELINE_DATA_DIR}
  batch_size: 1024
  model_name: microsoft/deberta-v3-large
  collate_fn:
    type: strategyqa-embedding-classification-collate-fn
    rationale_format: n
    max_input_length: 128