task:
  type: model-training
  batch_size: 4
  eval_batch_size: 32
  num_epochs: 20
  model:
    type: huggingface-wrapper
    model_handle: t5-base
  trainer:
    type: ecqa-irm-trainer
    optimizer_constructor:
      type: adamw
      learning_rate: 0.0001
    metrics:
      loss: 
        type: avg-loss
    eval_metrics:
      loss: 
        type: avg-loss
    main_metric: loss
    save_dir: ckpt/ecqa_${REV_MODEL_TYPE}_format=${RATIONALE_FORMAT}_ng=${NUM_NGRAMS}_mf=${MIN_FREQ}_mt=${MAX_TOKENS}_th=${THRESHOLD}_irm=${IRM_COEFFICIENT}
    device: "cuda:0"
  datapath_train: data/ecqa/rev_format=${RATIONALE_FORMAT}_ng=${NUM_NGRAMS}_mf=${MIN_FREQ}_mt=${MAX_TOKENS}_th=${THRESHOLD}/train
  datapath_eval: data/ecqa/rev_format=${RATIONALE_FORMAT}_ng=${NUM_NGRAMS}_mf=${MIN_FREQ}_mt=${MAX_TOKENS}_th=${THRESHOLD}/validation
  patience: 2