task:
  type: model-training
  batch_size: 4
  eval_batch_size: 32
  num_epochs: 20
  model:
    type: huggingface-wrapper
    model_handle: t5-base
  trainer:
    type: ecqa-irm-trainer
    irm_scheduler:
      type: step-scheduler
      start_val:
        - 0.0
      end_val:
        - ${IRM_COEFFICIENT}
      num_steps: 4
    optimizer_constructor:
      type: adamw
      learning_rate: 0.0001
    metrics:
      loss: 
        type: avg-loss
    eval_metrics:
      loss: 
        type: avg-loss
      accuracy:
        type: classification-accuracy
    main_metric: loss
    save_dir: ${REV_MODEL}
  datapath_train: ${REV_DATA_DIR}train
  datapath_eval: ${REV_DATA_DIR}validation
  patience: 2