task:
  type: model-training
  batch_size: ${REV_BATCH_SIZE}
  eval_batch_size: 32
  num_epochs: ${REV_EPOCHS}
  model:
    type: huggingface-wrapper
    model_handle: t5-base
  trainer:
    warmup_epochs: 2
    type: strategyqa-irm
    optimizer_constructor:
      type: adamw
      learning_rate: 0.0001
    irm_scheduler:
      type: step-scheduler
      start_val:
        - 0.0
      end_val:
        - ${IRM_COEFFICIENT}
      num_steps:
        - ${REV_EPOCHS}
    metrics:
      loss: 
        type: avg-loss
      factual_loss:
        type: stats-extractor
        indexing_path: "environment::factual.loss"
        reduction:
          type: "mean"
      counterfactual_loss:
        type: stats-extractor
        indexing_path: "environment::counterfactual.loss"
        reduction:
          type: "mean"
      factual_grad:
        type: stats-extractor
        indexing_path: "environment::factual.reg"
        reduction:
          type: "mean"
      counterfactual_grad:
        type: stats-extractor
        indexing_path: "environment::counterfactual.reg"
        reduction:
          type: "mean"
      accuracy:
        type: classification-accuracy
    eval_metrics:
      loss: 
        type: avg-loss
      accuracy:
        type: classification-accuracy
    main_metric: loss
    save_dir: ${REV_MODEL}
    device: "cuda:0"
  datapath_train: ${REV_DATA_DIR}train
  datapath_eval: ${REV_DATA_DIR}validation