task:
  type: model-training
  batch_size: ${REV_BATCH_SIZE}
  eval_batch_size: 32
  num_epochs: ${REV_EPOCHS}
  model:
    type: huggingface-wrapper
    model_handle: t5-base
  trainer:
    type: ecqa-baseline
    optimizer_constructor:
      type: adamw
      learning_rate: ${REV_LEARNING_RATE}
    metrics:
      loss:
        type: avg-loss
    eval_metrics:
      loss:
        type: avg-loss
      generation_accuracy:
        type: classification-accuracy
    main_metric: loss
    save_dir: ${BASELINE_MODEL}
  datapath_train: ${BASELINE_DATA_DIR}train
  datapath_eval: ${BASELINE_DATA_DIR}validation