task:
  type: model-training
  batch_size: ${REV_BATCH_SIZE}
  eval_batch_size: 32
  num_epochs: ${REV_EPOCHS}
  model:
    type: huggingface-classifier
    model_handle: microsoft/deberta-v3-large
    num_labels: 2
  trainer:
    type: strategyqa-classification-baseline
    optimizer_constructor:
      type: adamw
      learning_rate: ${REV_LEARNING_RATE}
    metrics:
      loss:
        type: avg-loss
      accuracy:
        type: classification-accuracy
    eval_metrics:
      loss:
        type: avg-loss
      accuracy:
        type: classification-accuracy
    main_metric: loss
    warmup_epochs: 0
    save_dir: ${BASELINE_MODEL}
  datapath_train: ${BASELINE_DATA_DIR}train
  datapath_eval: ${BASELINE_DATA_DIR}validation